export default [
        {
            "id":1,
            "college_name": "Hansraj College Delhi University - 1",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["Best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":2,
            "college_name": "Hansraj College Delhi University - 2",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["Best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":3,
            "college_name": "Hansraj College Delhi University - 3",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["Best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":4,
            "college_name": "Hansraj College Delhi University - 4",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["Best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":5,
            "college_name": "Hansraj College Delhi University - 5",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":6,
            "college_name": "Hansraj College Delhi University - 6",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":7,
            "college_name": "Hansraj College Delhi University - 7",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":8,
            "college_name": "Hansraj College Delhi University - 8",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":9,
            "college_name": "Hansraj College Delhi University - 9",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":10,
            "college_name": "Hansraj College Delhi University - 10",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":11,
            "college_name": "Hansraj College Delhi University - 11",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":12,
            "college_name": "Hansraj College Delhi University - 12",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":13,
            "college_name": "Hansraj College Delhi University - 13",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":15,
            "college_name": "Hansraj College Delhi University - 14",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":15,
            "college_name": "Hansraj College Delhi University - 15",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":16,
            "college_name": "Hansraj College Delhi University - 16",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":17,
            "college_name": "Hansraj College Delhi University - 17",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":18,
            "college_name": "Hansraj College Delhi University - 18",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":19,
            "college_name": "Hansraj College Delhi University - 19",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":20,
            "college_name": "Hansraj College Delhi University - 20",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":21,
            "college_name": "Hansraj College Delhi University - 21",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":22,
            "college_name": "Hansraj College Delhi University - 22",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":23,
            "college_name": "Hansraj College Delhi University - 23",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":24,
            "college_name": "Hansraj College Delhi University - 24",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":25,
            "college_name": "Hansraj College Delhi University - 25",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":26,
            "college_name": "Hansraj College Delhi University - 26",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":27,
            "college_name": "Hansraj College Delhi University - 27",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":28,
            "college_name": "Hansraj College Delhi University - 28",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":29,
            "college_name": "Hansraj College Delhi University - 29",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":30,
            "college_name": "Hansraj College Delhi University - 30",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":31,
            "college_name": "Hansraj College Delhi University - 31",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":32,
            "college_name": "Hansraj College Delhi University - 32",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":33,
            "college_name": "Hansraj College Delhi University - 33",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":34,
            "college_name": "Hansraj College Delhi University - 34",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":35,
            "college_name": "Hansraj College Delhi University - 35",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":36,
            "college_name": "Hansraj College Delhi University - 36",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":37,
            "college_name": "Hansraj College Delhi University - 37",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":38,
            "college_name": "Hansraj College Delhi University - 38",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":39,
            "college_name": "Hansraj College Delhi University - 39",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":40,
            "college_name": "Hansraj College Delhi University - 40",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":41,
            "college_name": "Hansraj College Delhi University - 41",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":42,
            "college_name": "Hansraj College Delhi University - 42",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":43,
            "college_name": "Hansraj College Delhi University - 43",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":44,
            "college_name": "Hansraj College Delhi University - 44",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":45,
            "college_name": "Hansraj College Delhi University - 45",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":46,
            "college_name": "Hansraj College Delhi University - 46",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":47,
            "college_name": "Hansraj College Delhi University - 47",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":48,
            "college_name": "Hansraj College Delhi University - 48",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":49,
            "college_name": "Hansraj College Delhi University - 49",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        },
        {
            "id":50,
            "college_name": "Hansraj College Delhi University - 50",
            "promoted": true,
            "discount": 20,
            "original_fees": 6000,
            "discounted_fees": 5200,
            "fees_cycle": "Per Semester (3months)",
            "image": "college.png",
            "ranking": "7 in 260 colleges in north campus",
            "tags": ["best colleges in 2018", "2kms away"],
            "amenties": ["Fee cancellation", "Free Wifi"],
            "rating": 4,
            "rating_remarks": "Very Good",
            "famous_nearest_places": "2.5kms from GTB Nagar, 7 Kms from Rajiv Chowk",
            "nearest_place": ["Near Vishwavidyalya Metro Station", "2 Kms away from bus stand"],
            "offertext": "Flat Rs2,000 off + upto Rs 500 wallet! to avail... LOGIN "
        }
    ]

